/*****************************************************************************
 *
 * Filename:
 * ---------
 *   custom_emi.c
 *
 * Project:
 * --------
 *   Android
 *
 * Description:
 * ------------
 *   This Module defines the EMI (external memory interface) related setting.
 *
 * Author:
 * -------
 *  EMI auto generator V0.01
 *
 *   Memory Device database last modified on 2017/6/29
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * $Revision$
 * $Modtime$
 * $Log$
 *
 *------------------------------------------------------------------------------
 * WARNING!!!  WARNING!!!   WARNING!!!  WARNING!!!  WARNING!!!  WARNING!!! 
 * This file is generated by EMI Auto-gen Tool.
 * Please do not modify the content directly!
 * It could be overwritten!
 *============================================================================
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

#include "mt_emi.h"
             
#define NUM_EMI_RECORD 6
             
int num_of_emi_records = NUM_EMI_RECORD ;
             
EMI_SETTINGS emi_settings[] =
{            
          {
        	   0x102,  /* TYPE  eMMC + LPDDR2 */
        	   {0x98,0xBC,0x90,0x66,0x76,0x16,0x08},  /* NAND_EMMC_ID */
        	   7,  /* EMMC and NAND ID/FW ID checking length */
        	   266,   /*EMI freq */
        	   0xAAAAAAAA,  /* EMI_DRVA_value */
        	   0x00AA0000,  /* EMI_DRVB_value */
        	   0x00000000,  /* EMI_ODLA_value */
        	   0x00000000,  /* EMI_ODLB_value */
        	   0x00000000,  /* EMI_ODLC_value */
        	   0x00000000,  /* EMI_ODLD_value */
        	   0x00000000,  /* EMI_ODLE_value */
        	   0x00000000,  /* EMI_ODLF_value */
        	   0x00000000,  /* EMI_ODLG_value */
        	   0x00000000,  /* EMI_ODLH_value */
        	   0x00000000,  /* EMI_ODLI_value */
        	   0x00000000,  /* EMI_ODLJ_value */
        	   0x00000000,  /* EMI_ODLK_value */
        	   0x00000000,  /* EMI_ODLL_value */
        	   0x00000000,  /* EMI_ODLM_value */
        	   0x00000000,  /* EMI_ODLN_value */
        	   
        	   0x02030000,  /* EMI_CONI_value */  /* set DRAM driving */
        	   0x4050265A,  /* EMI_CONJ_value */
        	   0x23051020,  /* EMI_CONK_value */
        	   0x60428098,  /* EMI_CONL_value */
        	   0x00350800,  /* EMI_CONN_value */  /* remember set bank number */
        	   
        	   0x00000000,  /* EMI_DUTA_value */
        	   0x00000000,  /* EMI_DUTB_value */
        	   0x00000000,  /* EMI_DUTC_value */
        	   
        	   0x00000000,  /* EMI_DUCA_value*/
        	   0x00000000,  /* EMI_DUCB_value*/
        	   0x00000000,  /* EMI_DUCE_value*/
        	   
        	   0x00030000,  /* EMI_IOCL_value */
        	   
        	   0x00010000,  /* EMI_GEND_value */
        	   
        	   {0x10000000, 0x00000000,0,0},  /* DRAM RANK SIZE  4Gb/rank */
        	   0x05,  /* DRAM vendor ID*/
                   0,  /* match flag*/

        },
        {
        	   0x102,  /* TYPE  eMMC + LPDDR2 */
        	   { 0x98,0xBC,0x90,0x66},  /* NAND_EMMC_ID */
        	   4,  /* EMMC and NAND ID/FW ID checking length */
        	   266,   /*EMI freq */
        	   0xAAAAAAAA,  /* EMI_DRVA_value */
        	   0x00AA0000,  /* EMI_DRVB_value */
        	   0x00000000,  /* EMI_ODLA_value */
        	   0x00000000,  /* EMI_ODLB_value */
        	   0x00000000,  /* EMI_ODLC_value */
        	   0x00000000,  /* EMI_ODLD_value */
        	   0x00000000,  /* EMI_ODLE_value */
        	   0x00000000,  /* EMI_ODLF_value */
        	   0x00000000,  /* EMI_ODLG_value */
        	   0x00000000,  /* EMI_ODLH_value */
        	   0x00000000,  /* EMI_ODLI_value */
        	   0x00000000,  /* EMI_ODLJ_value */
        	   0x00000000,  /* EMI_ODLK_value */
        	   0x00000000,  /* EMI_ODLL_value */
        	   0x00000000,  /* EMI_ODLM_value */
        	   0x00000000,  /* EMI_ODLN_value */
        	   
        	   0x02030000,  /* EMI_CONI_value */  /* set DRAM driving */
        	   0x40503763,  /* EMI_CONJ_value */
        	   0x23051020,  /* EMI_CONK_value */
        	   0x60428098,  /* EMI_CONL_value */
        	   0x00350800,  /* EMI_CONN_value */  /* remember set bank number */
        	   
        	   0x00000000,  /* EMI_DUTA_value */
        	   0x00000000,  /* EMI_DUTB_value */
        	   0x00000000,  /* EMI_DUTC_value */
        	   
        	   0x00000000,  /* EMI_DUCA_value*/
        	   0x00000000,  /* EMI_DUCB_value*/
        	   0x00000000,  /* EMI_DUCE_value*/
        	   
        	   0x00030000,  /* EMI_IOCL_value */
        	   
        	   0x00010000,  /* EMI_GEND_value */
        	   
        	   {0x10000000, 0x00000000,0,0},  /* DRAM RANK SIZE  4Gb/rank */
        	   0x03,  /* DRAM vendor ID*/
                   0,  /* match flag*/

        },
        {
        	   0x102,  /* TYPE  eMMC + LPDDR2 */
        	   { 0x98,0xBC,0x90,0x66,0x76,0x16,0x08},  /* NAND_EMMC_ID */
        	   7,  /* EMMC and NAND ID/FW ID checking length */
        	   266,   /*EMI freq */
        	   0xAAAAAAAA,  /* EMI_DRVA_value */
        	   0x00AA0000,  /* EMI_DRVB_value */
        	   0x00000000,  /* EMI_ODLA_value */
        	   0x00000000,  /* EMI_ODLB_value */
        	   0x00000000,  /* EMI_ODLC_value */
        	   0x00000000,  /* EMI_ODLD_value */
        	   0x00000000,  /* EMI_ODLE_value */
        	   0x00000000,  /* EMI_ODLF_value */
        	   0x00000000,  /* EMI_ODLG_value */
        	   0x00000000,  /* EMI_ODLH_value */
        	   0x00000000,  /* EMI_ODLI_value */
        	   0x00000000,  /* EMI_ODLJ_value */
        	   0x00000000,  /* EMI_ODLK_value */
        	   0x00000000,  /* EMI_ODLL_value */
        	   0x00000000,  /* EMI_ODLM_value */
        	   0x00000000,  /* EMI_ODLN_value */
        	   
        	   0x02030000,  /* EMI_CONI_value */  /* set DRAM driving */
        	   0x40503763,  /* EMI_CONJ_value */
        	   0x23051020,  /* EMI_CONK_value */
        	   0x60428098,  /* EMI_CONL_value */
        	   0x00350800,  /* EMI_CONN_value */  /* remember set bank number */
        	   
        	   0x00000000,  /* EMI_DUTA_value */
        	   0x00000000,  /* EMI_DUTB_value */
        	   0x00000000,  /* EMI_DUTC_value */
        	   
        	   0x00000000,  /* EMI_DUCA_value*/
        	   0x00000000,  /* EMI_DUCB_value*/
        	   0x00000000,  /* EMI_DUCE_value*/
        	   
        	   0x00030000,  /* EMI_IOCL_value */
        	   
        	   0x00010000,  /* EMI_GEND_value */
        	   
        	   {0x10000000, 0x00000000,0,0},  /* DRAM RANK SIZE  4Gb/rank */
        	   0x03,  /* DRAM vendor ID*/
                   0,  /* match flag*/

        },
        {
        	   0x102,  /* TYPE  eMMC + LPDDR2 */
        	   { 0x2C,0xBC,0x90,0x66,0x54},  /* NAND_EMMC_ID */
        	   5,  /* EMMC and NAND ID/FW ID checking length */
        	   266,   /*EMI freq */
        	   0xAAAAAAAA,  /* EMI_DRVA_value */
        	   0x00AA0000,  /* EMI_DRVB_value */
        	   0x00000000,  /* EMI_ODLA_value */
        	   0x00000000,  /* EMI_ODLB_value */
        	   0x00000000,  /* EMI_ODLC_value */
        	   0x00000000,  /* EMI_ODLD_value */
        	   0x00000000,  /* EMI_ODLE_value */
        	   0x00000000,  /* EMI_ODLF_value */
        	   0x00000000,  /* EMI_ODLG_value */
        	   0x00000000,  /* EMI_ODLH_value */
        	   0x00000000,  /* EMI_ODLI_value */
        	   0x00000000,  /* EMI_ODLJ_value */
        	   0x00000000,  /* EMI_ODLK_value */
        	   0x00000000,  /* EMI_ODLL_value */
        	   0x00000000,  /* EMI_ODLM_value */
        	   0x00000000,  /* EMI_ODLN_value */
        	   
        	   0x02030000,  /* EMI_CONI_value */  /* set DRAM driving */
        	   0x40503763,  /* EMI_CONJ_value */
        	   0x23051020,  /* EMI_CONK_value */
        	   0x60428098,  /* EMI_CONL_value */
        	   0x00350800,  /* EMI_CONN_value */  /* remember set bank number */
        	   
        	   0x00000000,  /* EMI_DUTA_value */
        	   0x00000000,  /* EMI_DUTB_value */
        	   0x00000000,  /* EMI_DUTC_value */
        	   
        	   0x00000000,  /* EMI_DUCA_value*/
        	   0x00000000,  /* EMI_DUCB_value*/
        	   0x00000000,  /* EMI_DUCE_value*/
        	   
        	   0x10030000,  /* EMI_IOCL_value */
        	   
        	   0x00010000,  /* EMI_GEND_value */
        	   
        	   {0x10000000, 0x00000000,0,0},  /* DRAM RANK SIZE  4Gb/rank */
        	   0x03,  /* DRAM vendor ID*/
                   0,  /* match flag*/

        },
        {
        	   0x102,  /* TYPE  eMMC + LPDDR2 */
        	   { 0xAD,0xBC,0x90,0x55,0x56},  /* NAND_EMMC_ID */
        	   5,  /* EMMC and NAND ID/FW ID checking length */
        	   266,   /*EMI freq */
        	   0xAAAAAAAA,  /* EMI_DRVA_value */
        	   0x00AA0000,  /* EMI_DRVB_value */
        	   0x00000000,  /* EMI_ODLA_value */
        	   0x00000000,  /* EMI_ODLB_value */
        	   0x00000000,  /* EMI_ODLC_value */
        	   0x00000000,  /* EMI_ODLD_value */
        	   0x00000000,  /* EMI_ODLE_value */
        	   0x00000000,  /* EMI_ODLF_value */
        	   0x00000000,  /* EMI_ODLG_value */
        	   0x00000000,  /* EMI_ODLH_value */
        	   0x00000000,  /* EMI_ODLI_value */
        	   0x00000000,  /* EMI_ODLJ_value */
        	   0x00000000,  /* EMI_ODLK_value */
        	   0x00000000,  /* EMI_ODLL_value */
        	   0x00000000,  /* EMI_ODLM_value */
        	   0x00000000,  /* EMI_ODLN_value */
        	   
        	   0x02030000,  /* EMI_CONI_value */  /* set DRAM driving */
        	   0x40503763,  /* EMI_CONJ_value */
        	   0x23051020,  /* EMI_CONK_value */
        	   0x60428098,  /* EMI_CONL_value */
        	   0x00350800,  /* EMI_CONN_value */  /* remember set bank number */
        	   
        	   0x00000000,  /* EMI_DUTA_value */
        	   0x00000000,  /* EMI_DUTB_value */
        	   0x00000000,  /* EMI_DUTC_value */
        	   
        	   0x00000000,  /* EMI_DUCA_value*/
        	   0x00000000,  /* EMI_DUCB_value*/
        	   0x00000000,  /* EMI_DUCE_value*/
        	   
        	   0x00030000,  /* EMI_IOCL_value */
        	   
        	   0x00010000,  /* EMI_GEND_value */
        	   
        	   {0x10000000, 0x00000000,0,0},  /* DRAM RANK SIZE  4Gb/rank */
        	   0x06,  /* DRAM vendor ID*/
                   0,  /* match flag*/

        },
        {
        	   0x102,  /* TYPE  eMMC + LPDDR2 */
        	   { 0x01,0xBC,0x90,0x55,0x56},  /* NAND_EMMC_ID */
        	   5,  /* EMMC and NAND ID/FW ID checking length */
        	   266,   /*EMI freq */
        	   0xAAAAAAAA,  /* EMI_DRVA_value */
        	   0x00AA0000,  /* EMI_DRVB_value */
        	   0x00000000,  /* EMI_ODLA_value */
        	   0x00000000,  /* EMI_ODLB_value */
        	   0x00000000,  /* EMI_ODLC_value */
        	   0x00000000,  /* EMI_ODLD_value */
        	   0x00000000,  /* EMI_ODLE_value */
        	   0x00000000,  /* EMI_ODLF_value */
        	   0x00000000,  /* EMI_ODLG_value */
        	   0x00000000,  /* EMI_ODLH_value */
        	   0x00000000,  /* EMI_ODLI_value */
        	   0x00000000,  /* EMI_ODLJ_value */
        	   0x00000000,  /* EMI_ODLK_value */
        	   0x00000000,  /* EMI_ODLL_value */
        	   0x00000000,  /* EMI_ODLM_value */
        	   0x00000000,  /* EMI_ODLN_value */
        	   
        	   0x02030000,  /* EMI_CONI_value */  /* set DRAM driving */
        	   0x4050365A,  /* EMI_CONJ_value */
        	   0x23051020,  /* EMI_CONK_value */
        	   0x60428098,  /* EMI_CONL_value */
        	   0x00350800,  /* EMI_CONN_value */  /* remember set bank number */
        	   
        	   0x00000000,  /* EMI_DUTA_value */
        	   0x00000000,  /* EMI_DUTB_value */
        	   0x00000000,  /* EMI_DUTC_value */
        	   
        	   0x00000000,  /* EMI_DUCA_value*/
        	   0x00000000,  /* EMI_DUCB_value*/
        	   0x00000000,  /* EMI_DUCE_value*/
        	   
        	   0x00030000,  /* EMI_IOCL_value */
        	   
        	   0x00010000,  /* EMI_GEND_value */
        	   
        	   {0x10000000, 0x00000000,0,0},  /* DRAM RANK SIZE  4Gb/rank */
        	   0x05,  /* DRAM vendor ID*/
                   0,  /* match flag*/

        }

}; 
