/*
 * Generated by MTK SP DrvGen Version 03.13.6  for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Mon Apr  1 20:04:45 2019
 * Do Not Modify the File.
 */

#define GPIO_DVDD28_BPI     GPIO_VIO28
#define GPIO_DVDD3_LCD     GPIO_VIO18
#define MSDC_POWER_MC1     MSDC_VMC


