/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Tue Apr  2 19:32:26 2019
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


