/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6  for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Tue Apr  2 19:32:26 2019
 * Do Not Modify the File.
 */



#include <linux/types.h>
#include <mach/mt_typedefs.h>
#include <mach/mt_pm_ldo.h>


void pmu_drv_tool_customization_init(void)
{
}




